# @Author: Mukhil Sundararaj
# @Date:   2021-09-21 10:16:54
# @Last Modified by:   Mukhil Sundararaj
# @Last Modified time: 2021-10-28 16:47:35
version: '3.3'

services:
  fakegram-backend:
    depends_on:
      - mongo
    stdin_open: true
    container_name: fakegram-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fakegram
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
